apiVersion: v1
clusters:
- cluster:
    server: https://BE99174EBD87741CF0DB2089D2C974F5.gr7.us-east-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EVXlNakUzTWpreE0xb1hEVE13TURVeU1ERTNNamt4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDF5CkdLTFZJNzFCWTBXYWhzU2o1K3owQ29VSTJobnRBWk9pVlBUNEM3eGlDdmxqV2JEMkdrUnkxTkE2Y0gycHQ4Z1AKUjAwTkZGK2E5cGQrSEhDYng0dFdRb296UUZJQWg5SWpaR3JvNTBuQm52ZzUvSlRhSldMd0g1N2dMK055ZUNSMQpmTWVlZUNaYkZ1Y1FRQktxbG1JTnFQK3lFbzVJc215c1ZCNFNjQXhTWlQxdWtyU3ZacW9STkpuQnpmeURTMnFaCnZWZjZhbUhMbzBScDZoNzFiYUkwdkx4TFBHV3BsTXJJZVZhbFk1elNxelMyaTUvVHJ1QWZWMUtBZzNBZWIzMmMKU2pMdk1TeDV4NnZNS0VPU1oxUGo2cTZHMXIwVlhFcnlhVmxLdkl1UWgzb2xtcUp5WHZ1blFKYmk2WlNLTGtCawo5aVplMU9yemVES0g1YlVENFhVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHOXJMWWc1VjdKYjIxZDFUdVJIVU1wa0VaMmIKVm9kclhZUExHclpKVGtNRUdFa3BNdjN6bXVUR0dUcUFicFl6SERlNytSSGZjL2JucDgybGR4S2RZUCs0dlROOApOcHBnK1RsODF6ayswSU5DSUZKSFhlS3hCdFJVdld5YVBXalFkVWhXUlJBWEZqbzljeWhxa0pEaU5LRU9oZ2VKCnN2cmVCbHlwTG9TWmFuUlIvOWd1Q0c5Z29uelJhLzlKbHNuWXZVWmw5cXI1YnVreGtNc3J4dVU4ZC9IdWlvcGIKbzlKL1g1Qk1vWjRESGhLNTUrU210YWpWOExKNU5GRHlpd21GQkE1ME1oTHhzZkR5a2tsTGpEQjRnbUhIbVU0TQptTWxYaU13c2VwMVdtbitWZXZ6SkU2SjZFT3R3L0NmUnBRRUpLdkFpaXhPODREd21VNkMvcmRtd0ZTVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=\n  name: eks_Clustereks-codePip01\n\ncontexts:\n- context:\n    cluster: eks_Clustereks-codePip01
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "dev-eks-terraform"
